PRAGMA foreign_keys = 1;

CREATE TABLE IF NOT EXISTS `user` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `username` TEXT NOT NULL,
    'email' TEXT NOT NULL,
    'password' TEXT NOT NULL,
    `role` TEXT NOT NULL,
    `reg_date` TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS `book` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `name` TEXT NOT NULL,
    `authors` TEXT NOT NULL,
    `price` REAL NOT NULL,
    `length` INTEGER NOT NULL,
    `is_available` BOOL NOT NULL,
    `source` BLOB NOT NULL,
    `image` BLOB,
    `recieve_date` TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS `genre` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `name` TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS `book_genre` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `book_id` INTEGER NOT NULL REFERENCES `book`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    `genre_id` INTEGER NOT NULL REFERENCES `genre`(`id`) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `order` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `user_id` INTEGER NOT NULL REFERENCES `user`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    `datetime` TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS `order_book` (
    `id` INTEGER PRIMARY KEY AUTOINCREMENT,
    `order_id` INTEGER NOT NULL REFERENCES `order`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    `book_id` INTEGER NOT NULL REFERENCES `book`(`id`) ON UPDATE CASCADE ON DELETE CASCADE,
    `quantity` INTEGER NOT NULL
);